<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mouad_ben"
 *
 * Auto generated by Extension Builder 2014-08-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Benabdennour',
	'description' => 'Configures Template',
	'category' => 'example',
	'author' => 'Mouad Benabdennour',
	'author_email' => 'mouadbenabdennour@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			't3jquery' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);